#!/usr/bin/env python3
"""
Combine scene videos with audio descriptions into a single video.

Each scene is preceded by its narration played over a black screen.
Requires ffmpeg. Resolution and frame rate are auto-detected from the
first scene clip unless overridden.

Usage:
  python combine_video.py scenes/Kilavuz_scenes.csv -o final.mp4
  python combine_video.py scenes/Kilavuz_scenes.csv --audio-dir scenes/audio -o final.mp4
"""

import argparse
import json
import shutil
import subprocess
import sys
import tempfile
import time
from pathlib import Path
from typing import Optional

from utils import get_ffmpeg_exe, load_scenes_csv, log_run

LOG_PREFIX = "[combine]"
AUDIO_SAMPLE_RATE = 48000
AUDIO_CHANNELS = 2


def _timecode_to_seconds(tc: str) -> float:
    """Parse MM:SS.f or HH:MM:SS.f timecode into seconds."""
    parts = tc.replace(",", ".").split(":")
    if len(parts) == 3:
        return float(parts[0]) * 3600 + float(parts[1]) * 60 + float(parts[2])
    if len(parts) == 2:
        return float(parts[0]) * 60 + float(parts[1])
    return float(tc)


# ---------------------------------------------------------------------------
# FFprobe helpers
# ---------------------------------------------------------------------------

def _get_ffprobe(ffmpeg: str) -> Optional[str]:
    """Derive ffprobe path from the ffmpeg binary."""
    probe = Path(ffmpeg).with_name(
        Path(ffmpeg).name.replace("ffmpeg", "ffprobe")
    )
    if probe.is_file():
        return str(probe)
    return shutil.which("ffprobe")


def _probe_video(path: str, ffprobe: str) -> dict:
    """Return {width, height, fps, has_audio} for a video file."""
    try:
        r = subprocess.run(
            [ffprobe, "-v", "quiet", "-print_format", "json",
             "-show_streams", path],
            capture_output=True, text=True, timeout=15,
        )
        streams = json.loads(r.stdout).get("streams", [])
        vs = next(
            (s for s in streams if s.get("codec_type") == "video"), None,
        )
        if not vs:
            return {}
        rfr = vs.get("r_frame_rate", "25/1")
        parts = (rfr.split("/") + ["1"])[:2]
        fps = round(float(parts[0]) / float(parts[1]), 3)
        return {
            "width": int(vs["width"]),
            "height": int(vs["height"]),
            "fps": fps,
            "has_audio": any(
                s.get("codec_type") == "audio" for s in streams
            ),
        }
    except Exception:
        return {}


# ---------------------------------------------------------------------------
# FFmpeg clip builders
# ---------------------------------------------------------------------------

def _make_audio_clip(
    audio: Path, out: Path, ffmpeg: str,
    w: int, h: int, fps: float,
) -> None:
    """Create a black-screen video clip from an audio file."""
    subprocess.run([
        ffmpeg, "-y",
        "-f", "lavfi", "-i", f"color=c=black:s={w}x{h}:r={fps}",
        "-i", str(audio),
        "-c:v", "libx264", "-tune", "stillimage",
        "-c:a", "aac", "-b:a", "192k",
        "-ar", str(AUDIO_SAMPLE_RATE), "-ac", str(AUDIO_CHANNELS),
        "-pix_fmt", "yuv420p", "-shortest",
        str(out),
    ], check=True, capture_output=True)


def _normalize_clip(
    src: Path, out: Path, ffmpeg: str,
    w: int, h: int, fps: float, add_silent_audio: bool,
    duration: Optional[float] = None,
) -> None:
    """Re-encode a video clip to a uniform format for concatenation."""
    cmd = [ffmpeg, "-y", "-i", str(src)]
    if add_silent_audio:
        cmd += ["-f", "lavfi", "-i",
                f"anullsrc=r={AUDIO_SAMPLE_RATE}:cl=stereo",
                "-shortest"]
    cmd += [
        "-c:v", "libx264", "-c:a", "aac", "-b:a", "192k",
        "-ar", str(AUDIO_SAMPLE_RATE), "-ac", str(AUDIO_CHANNELS),
        "-pix_fmt", "yuv420p",
        "-r", str(fps),
        "-s", f"{w}x{h}",
    ]
    if duration is not None:
        cmd += ["-t", f"{duration:.3f}"]
    cmd.append(str(out))
    subprocess.run(cmd, check=True, capture_output=True)


# ---------------------------------------------------------------------------
# File lookup helpers
# ---------------------------------------------------------------------------

def _find_scene_video(
    scenes_dir: Path, stem: str, sid: int,
) -> Optional[Path]:
    """Find the scene video file, trying common zero-padding widths."""
    for pad in (3, 2, 4, 1):
        p = scenes_dir / f"{stem}-Scene-{sid:0{pad}d}.mp4"
        if p.is_file():
            return p
    return None


def _find_audio(
    audio_dir: Path, stem: str, sid: int,
) -> Optional[Path]:
    """Find the per-scene audio .wav generated by generate_audio.py."""
    p = audio_dir / f"{stem}_scene_{sid}.wav"
    return p if p.is_file() else None


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Combine scene videos with audio descriptions "
                    "into one video.",
    )
    parser.add_argument("csv", help="Scene CSV file (from split_scenes)")
    parser.add_argument(
        "--audio-dir",
        help="Directory with per-scene .wav files "
             "(default: same directory as the CSV)",
    )
    parser.add_argument(
        "-o", "--output", default="combined_output.mp4",
        help="Output video path (default: combined_output.mp4)",
    )
    parser.add_argument(
        "--resolution", metavar="WxH",
        help="Force output resolution (auto-detected if omitted)",
    )
    parser.add_argument(
        "--fps", type=float,
        help="Force frame rate (auto-detected if omitted)",
    )
    parser.add_argument(
        "--keep-temp", action="store_true",
        help="Keep intermediate files for debugging",
    )
    args = parser.parse_args()

    csv_path = Path(args.csv)
    if not csv_path.is_file():
        print(f"Error: CSV not found: {csv_path}", file=sys.stderr)
        sys.exit(1)

    ffmpeg = get_ffmpeg_exe()
    if not ffmpeg:
        print("Error: ffmpeg not found. Install ffmpeg or imageio-ffmpeg.",
              file=sys.stderr)
        sys.exit(1)

    scenes_dir = csv_path.parent
    audio_dir = Path(args.audio_dir) if args.audio_dir else scenes_dir
    video_stem = csv_path.stem.replace("_scenes", "")

    rows = load_scenes_csv(csv_path)
    if not rows:
        print("Error: CSV is empty.", file=sys.stderr)
        sys.exit(1)

    # Gather entries: (scene_id, scene_video_path, audio_path_or_None, duration_s)
    entries: list[tuple[int, Path, Optional[Path], float]] = []
    for row in rows:
        sid = int(row["scene_id"])
        scene_path = _find_scene_video(scenes_dir, video_stem, sid)
        if not scene_path:
            print(f"{LOG_PREFIX} scene {sid}: video not found, skipping",
                  file=sys.stderr)
            continue
        audio_path = _find_audio(audio_dir, video_stem, sid)
        if not audio_path:
            print(f"{LOG_PREFIX} scene {sid}: no audio, "
                  "will include video only", file=sys.stderr)
        duration = (_timecode_to_seconds(row["end_time"])
                    - _timecode_to_seconds(row["start_time"]))
        entries.append((sid, scene_path, audio_path, duration))

    if not entries:
        print("Error: No scene video files found.", file=sys.stderr)
        sys.exit(1)

    audio_count = sum(1 for _, _, a, _ in entries if a)
    print(f"{LOG_PREFIX} {len(entries)} scene(s), {audio_count} with audio",
          file=sys.stderr)

    # Auto-detect format from first scene video
    ffprobe = _get_ffprobe(ffmpeg)
    info: dict = {}
    if ffprobe:
        info = _probe_video(str(entries[0][1]), ffprobe)

    if args.resolution:
        w, h = (int(x) for x in args.resolution.lower().split("x"))
    else:
        w = info.get("width", 1920)
        h = info.get("height", 1080)

    fps = args.fps or info.get("fps", 25.0)
    has_audio_stream = info.get("has_audio", True)

    print(f"{LOG_PREFIX} format: {w}x{h} @ {fps} fps, "
          f"source has audio: {has_audio_stream}", file=sys.stderr)

    # Process clips in a temp directory
    tmp = Path(tempfile.mkdtemp(prefix="combine_"))
    t_start = time.perf_counter()
    try:
        concat_parts: list[Path] = []

        for i, (sid, scene_path, audio_path, duration) in enumerate(entries):
            if audio_path:
                audio_clip = tmp / f"{i:03d}_a_desc.mp4"
                print(f"{LOG_PREFIX} scene {sid}: encoding audio clip",
                      file=sys.stderr)
                _make_audio_clip(audio_path, audio_clip, ffmpeg, w, h, fps)
                concat_parts.append(audio_clip)

            norm_clip = tmp / f"{i:03d}_b_scene.mp4"
            print(f"{LOG_PREFIX} scene {sid}: normalizing video "
                  f"({duration:.1f}s)", file=sys.stderr)
            _normalize_clip(
                scene_path, norm_clip, ffmpeg, w, h, fps,
                add_silent_audio=not has_audio_stream,
                duration=duration,
            )
            concat_parts.append(norm_clip)

        # Write concat list
        list_file = tmp / "concat.txt"
        with open(list_file, "w", encoding="utf-8") as f:
            for p in concat_parts:
                f.write(f"file '{p.as_posix()}'\n")

        # Concatenate
        out_path = Path(args.output)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        print(f"{LOG_PREFIX} concatenating {len(concat_parts)} clips "
              f"-> {out_path}", file=sys.stderr)
        subprocess.run([
            ffmpeg, "-y",
            "-f", "concat", "-safe", "0",
            "-i", str(list_file),
            "-c", "copy",
            str(out_path),
        ], check=True)

        elapsed = time.perf_counter() - t_start
        print(f"{LOG_PREFIX} done in {elapsed:.1f}s: {out_path}",
              file=sys.stderr)

    finally:
        if args.keep_temp:
            print(f"{LOG_PREFIX} temp files kept at: {tmp}",
                  file=sys.stderr)
        else:
            shutil.rmtree(tmp, ignore_errors=True)

    log_run("combine_video.py", {
        "csv": str(csv_path),
        "audio_dir": str(audio_dir),
        "scenes": len(entries),
        "scenes_with_audio": audio_count,
        "resolution": f"{w}x{h}",
        "fps": fps,
    }, elapsed, [str(out_path)])


if __name__ == "__main__":
    main()
